--==========================
-- Part-to-whole Analysis --
--==========================

-- percentage of platform used to order
select
PURCHASE_PLATFORM as purchase_platform, 
count (distinct order_id) as total_order,
ROUND (COUNT(DISTINCT order_id) * 100.0 / SUM(COUNT(DISTINCT order_id)) OVER () , 2)  AS pct_of_total_orders
from gamezoneClean
where PURCHASE_PLATFORM is not null
group by PURCHASE_PLATFORM
order by purchase_platform

-- percentage of marketing channels used to order
select
marketing_channel_clean as marketing_channel,
COUNT(DISTINCT order_id) AS total_order,
ROUND (COUNT(DISTINCT order_id) * 100.0 / SUM(COUNT(DISTINCT order_id)) OVER (), 2) AS pct_of_total_orders
from gamezoneClean
WHERE MARKETING_CHANNEL_CLEAN IS NOT NULL
  AND MARKETING_CHANNEL_CLEAN <> 'unknown'
group by MARKETING_CHANNEL_CLEAN
order by marketing_channel

-- percentage of sales generated by marketing channel
select
marketing_channel_clean as marketing_channel,
sum(usd_price) as total_sales,
ROUND (SUM(usd_price) * 100.0 / SUM(SUM(usd_price)) OVER (),2) AS pct_of_total_sales
from gamezoneClean
where MARKETING_CHANNEL_CLEAN is not null
  AND MARKETING_CHANNEL_CLEAN <> 'unknown'
and USD_PRICE <> 0
group by MARKETING_CHANNEL_CLEAN
order by marketing_channel

-- percentage of sales generated by platforms
select
PURCHASE_PLATFORM as purchase_platform,
sum(usd_price) as total_sales,
ROUND (SUM(usd_price) * 100.0 / SUM(SUM(usd_price)) OVER (), 2) AS pct_of_total_sales
from gamezoneClean
where PURCHASE_PLATFORM is not null
and USD_PRICE <> 0
group by PURCHASE_PLATFORM
order by purchase_platform

